author: Chris Basham
description: Chris Basham is a designer and front-end developer living in Bloomington, Indiana.
email: chris@bash.am
elsewhere:
  CodePen: https://codepen.io/basham
  GitHub: https://github.com/basham
  Twitter: https://twitter.com/chrisbasham
repo: https://github.com/basham/v4.bash.am
new_issue: https://github.com/basham/v4.bash.am/issues/new
