author: Chris Basham
specialty: Interaction designer & Front-end developer
description: Chris Basham is an interaction designer and front-end developer living in Bloomington, Indiana.
twitter: chrisbasham
email: chris@bash.am
phone: (812) 459-9891
phone_tel: +18124599891
