author: Chris Basham
description: Chris Basham is an interaction designer and front-end developer living in Bloomington, Indiana.
twitter: chrisbasham
email: chris@bash.am
elsewhere:
  CodePen: http://codepen.io/basham
  Flickr: https://www.flickr.com/photos/chrisbasham
  GitHub: https://github.com/basham
  Kickstarter: https://www.kickstarter.com/profile/basham
  LinkedIn: http://www.linkedin.com/in/cbasham
  Speaker Deck: https://speakerdeck.com/basham
  Twitter: https://twitter.com/chrisbasham
  Vimeo: http://vimeo.com/basham
repo: https://github.com/basham/v4.bash.am
new_issue: https://github.com/basham/v4.bash.am/issues/new
ixda_bloomington: https://www.facebook.com/ixdabloomington
